# Generated by Django 4.1.8 on 2023-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("Forearms", "Forearms"),
                            ("Triceps", "Triceps"),
                            ("Biceps", "Biceps"),
                            ("Neck", "Neck"),
                            ("Shoulders", "Shoulders"),
                            ("Chest", "Chest"),
                            ("Back", "Back"),
                            ("Core", "Core"),
                            ("Upper Legs", "Upper Legs"),
                            ("Glutes", "Glutes"),
                            ("Calves", "Calves"),
                            ("Full Body", "Full Body"),
                            ("Other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("Barbell", "Barbell"),
                            ("Dumbbell", "Dumbbell"),
                            ("Machine", "Machine"),
                            ("Bodyweight", "Bodyweight"),
                            ("Bands", "Bands"),
                            ("Cardio", "Cardio"),
                            ("Other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
    ]
